- name: CVE-2023-51042 - kernel, kernel-tools-libs and 4 more
  ansible.builtin.dnf:
    state: latest
    name:
      - kernel-5.14.0-570.51.1.el9_6
      - kernel-tools-libs-5.14.0-570.51.1.el9_6
      - kernel-tools-5.14.0-570.51.1.el9_6
      - kernel-modules-core-5.14.0-570.51.1.el9_6
      - kernel-core-5.14.0-570.51.1.el9_6
      - kernel-modules-5.14.0-570.51.1.el9_6

- name: CVE-2024-25062 - libxml2
  ansible.builtin.dnf:
    name: libxml2-2.9.13-6.el9_4
    state: latest

- name: CVE-2024-2961 - libnsl, glibc-devel and 5 more
  ansible.builtin.dnf:
    name: "{{ item }}-2.34-100.el9_4.4"
    state: latest
  loop:
    - libnsl
    - glibc-devel
    - glibc-minimal-langpack
    - glibc-gconv-extra
    - glibc-common
    - glibc

- name: Install SSM agent
  ansible.builtin.shell: dnf install https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm -y
